pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run lint
    npm run build
  displayName: 'Build the package'

- script: |
    npm test
  displayName: 'Test the code'
