trigger:
    - dev
    - staging
    - master

pool:
    vmImage: 'windows-latest'

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
          npm install
          npm run lint
          npm run build
      displayName: 'Build the package'

    - script: |
          npm test
      displayName: 'Test the code'

    - script: |
          npm pack
      displayName: 'Package'

    - task: CopyFiles@2
      inputs:
          contents: '*.tgz'
          targetFolder: $(Build.ArtifactStagingDirectory)
      displayName: 'Copy archives to artifacts staging directory'

    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: 'Package'
      displayName: 'Publish artifacts'
