pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        npm install
        npm run lint
        npm run build
    displayName: 'Build the package'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        npm run link-dev-package
    displayName: 'Link the package'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        npm test
    displayName: 'Test the code'